---
# tasks file for wordpress

- name: Verificando se ja foi configurado algum site
  stat: path={{ diretorio_site }}/wp-login.php
  register: stat_result
  notify: restart nginx

- name: Download WordPress
  shell: cd {{ diretorio_site }} && wget http://wordpress.org/latest.tar.gz && tar xfz latest.tar.gz && cd wordpress && mv * ../ && cd .. && rm -rf wordpress/ && rm latest.tar.gz
  when: not stat_result.stat.exists
  notify: restart nginx

- name: Restart PHP
  shell: /etc/init.d/*-fpm restart


